import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/providers/auth";
import Header from "../components/header";
import ToastProvider from "@/providers/toast";

export const metadata: Metadata = {
  title: "Finance Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastProvider>
            <div className="flex h-screen flex-col">
              <div>
                <Header />
              </div>
              <div className="flex-1">{children}</div>
            </div>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
